extend_range: 2
height_threshold: 1
horizontal_left: 180
horizontal_resolution: 0.199
horizontal_right: -180
lidar_position: !!python/tuple
- 0
- 0
- 0
noise:
  loss_rate: 0.1
  noise_average: 0
  noise_severity: 0.1
  noise_variance: 0.03
r: 1
range: 200
vertical_down: 25
vertical_up: -15
vertical_resolution: 0.675
evaluate_angle: !!python/object/apply:collections.OrderedDict
- - - 1
    - -25.1
  - - 2
    - -16.07
  - - 3
    - -11.78
  - - 4
    - -9.27
  - - 5
    - -7.67
  - - 6
    - -6.87
  - - 7
    - -6.52
  - - 8
    - -6.31
  - - 9
    - -6.1
  - - 10
    - -5.91
  - - 11
    - -5.71
  - - 12
    - -5.51
  - - 13
    - -5.3
  - - 14
    - -5.1
  - - 15
    - -4.9
  - - 16
    - -4.7
  - - 17
    - -4.5
  - - 18
    - -4.3
  - - 19
    - -4.1
  - - 20
    - -3.9
  - - 21
    - -3.7
  - - 22
    - -3.5
  - - 23
    - -3.3
  - - 24
    - -3.1
  - - 25
    - -2.9
  - - 26
    - -2.7
  - - 27
    - -2.5
  - - 28
    - -2.3
  - - 29
    - -2.09
  - - 30
    - -1.9
  - - 31
    - -1.69
  - - 32
    - -1.49
  - - 33
    - -1.29
  - - 34
    - -1.09
  - - 35
    - -0.89
  - - 36
    - -0.69
  - - 37
    - -0.49
  - - 38
    - -0.29
  - - 39
    - -0.09
  - - 40
    - 0.11
  - - 41
    - 0.31
  - - 42
    - 0.51
  - - 43
    - 0.71
  - - 44
    - 0.91
  - - 45
    - 1.11
  - - 46
    - 1.31
  - - 47
    - 1.51
  - - 48
    - 1.71
  - - 49
    - 1.91
  - - 50
    - 2.12
  - - 51
    - 2.32
  - - 52
    - 2.52
  - - 53
    - 2.72
  - - 54
    - 2.92
  - - 55
    - 3.12
  - - 56
    - 3.32
  - - 57
    - 3.52
  - - 58
    - 3.72
  - - 59
    - 3.97
  - - 60
    - 4.42
  - - 61
    - 5.07
  - - 62
    - 5.98
  - - 63
    - 7.43
  - - 64
    - 11.53
